console.log('start');
var sound = document.querySelector('.sound').querySelectorAll('audio');
document.addEventListener('keydown', e => {
    console.log(e.keyCode + ',', 'Ctrl: ' + e.ctrlKey, 'Alt: ' + e.altKey, 'Shift: ' + e.shiftKey);
    switch (e.key) {
        case 'a': sound[0].play();
            break;
        case 'b': sound[1].play();
            break;
        case 'c': sound[2].play();
            break;
        case 'd': sound[3].play();
            break;
        case 'e': sound[4].play();
            break;
        case 'f': sound[5].play();
            break;
        case 'g': sound[6].play();
            break;
        case 'h': sound[7].play();
            break;
        case 'i': sound[8].play();
            break;
        case 'j': sound[9].play();
            break;
        case 'k': sound[10].play();
            break;
        case 'l': sound[11].play();
            break;
        case 'm': sound[12].play();
            break;
        case 'n': sound[13].play();
            break;
        case 'o': sound[14].play();
            break;
        case 'p': sound[15].play();
            break;
        case 'q': sound[16].play();
            break;
        case 'r': sound[17].play();
            break;
        case 's': sound[18].play();
            break;
        case 't': sound[19].play();
            break;
        case 'u': sound[20].play();
            break;
        case 'v': sound[21].play();
            break;
        case 'w': sound[22].play();
            break;
        case 'x': sound[23].play();
            break;
        case 'y': sound[24].play();
            break;
        case 'z': sound[25].play();
            break;
        case 'A': sound[26].play();
            break;
        case 'B': sound[27].play();
            break;
        case 'C': sound[28].play();
            break;
        case 'D': sound[29].play();
            break;
        case 'E': sound[30].play();
            break;
        case 'F': sound[31].play();
            break;
        case 'G': sound[32].play();
            break;
        case 'H': sound[33].play();
            break;
        case 'I': sound[34].play();
            break;
        case 'J': sound[35].play();
            break;
        case 'K': sound[36].play();
            break;
        case 'L': sound[37].play();
            break;
        case 'M': sound[38].play();
            break;
        case 'N': sound[39].play();
            break;
        case 'O': sound[40].play();
            break;
        case 'P': sound[41].play();
            break;
        case 'Q': sound[42].play();
            break;
        case 'R': sound[43].play();
            break;
        case 'S': sound[44].play();
            break;
        case 'T': sound[45].play();
            break;
        case 'U': sound[46].play();
            break;
        case 'V': sound[47].play();
            break;
        case 'W': sound[48].play();
            break;
        case 'X': sound[49].play();
            break;
        case 'Y': sound[50].play();
            break;
        case 'Z': sound[51].play();
            break;
        case '1': sound[52].play();
            break;
        case '2': sound[53].play();
            break;
        case '3': sound[54].play();
            break;
        case '4': sound[55].play();
            break;
        case '5': sound[56].play();
            break;
        case '6': sound[57].play();
            break;
        case '7': sound[58].play();
            break;
        case '8': sound[59].play();
            break;
        case '9': sound[60].play();
            break;
        case '0': sound[61].play();
            break;
        case '[': sound[62].play();
            break;
        case ']': sound[63].play();
            break;
        case '\\': sound[64].play();
            break;
        case ';': sound[65].play();
            break;
        case '\'': sound[66].play();
            break;
        case ',': sound[67].play();
            break;
        case '.': sound[68].play();
            break;
        case '/': sound[69].play();
            break;
        case '!': sound[70].play();
            break;
        case '@': sound[71].play();
            break;
        case '#': sound[72].play();
            break;
        case '$': sound[73].play();
            break;
        case '%': sound[74].play();
            break;
        case '^': sound[75].play();
            break;
        case '&': sound[76].play();
            break;
        case '*': sound[77].play();
            break;
        case '(': sound[78].play();
            break;
        case ')': sound[79].play();
            break;
        case '{': sound[80].play();
            break;
        case '}': sound[81].play();
            break;
        case '|': sound[82].play();
            break;
        case ':': sound[83].play();
            break;
        case '"': sound[84].play();
            break;
        case '<': sound[85].play();
            break;
        case '>': sound[86].play();
            break;
        case '?': sound[87].play();
            break;
        default: return false;
    }
});